### ISSUE TITLE
true is not iterable while installing sdk

### ISSUE THREAD

**Issue by trubi** [harness/ff-javascript-client-sdk#28]
Hello harness people,
when installing ff sdk to my project (latest version 1.4.9), yarn install fails with

```
Yarn version: 
  1.22.17

Node version: 
  14.18.1

Platform: 
  darwin x64

Trace: 
  TypeError: true is not iterable!
      at module.exports.module.exports.__webpack_require__.getIterator (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:105587:42)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:48787:192)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:5301:28)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:307:12)
      at PackageLinker.linkBinDependencies (/usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:48834:20)
      at /usr/local/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:49400:28
```

when tryin 1.4.7, all looks fine.

**Comment by enver-bisevac** [comment]
Hi @trubi, pull request [PR67](https://github.com/harness/ff-javascript-client-sdk/pull/29) was created. pls try rc version:
yarn add @harnessio/ff-javascript-client-sdk@1.4.10-rc1
